In [1]:
import torch

### `torch.stack` 按维度堆叠

In [6]:
a = torch.ones(1, 3, 4)
b = torch.ones(1, 3, 4) * 2

In [7]:
x = torch.stack((a, b), dim=0)
x, x.shape

(tensor([[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],
 
 
         [[[2., 2., 2., 2.],
           [2., 2., 2., 2.],
           [2., 2., 2., 2.]]]]),
 torch.Size([2, 1, 3, 4]))

In [8]:
x = torch.stack((a, b), dim=1)
x, x.shape

(tensor([[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[2., 2., 2., 2.],
           [2., 2., 2., 2.],
           [2., 2., 2., 2.]]]]),
 torch.Size([1, 2, 3, 4]))

In [9]:
x = torch.stack((a, b), dim=-1)
x, x.shape

(tensor([[[[1., 2.],
           [1., 2.],
           [1., 2.],
           [1., 2.]],
 
          [[1., 2.],
           [1., 2.],
           [1., 2.],
           [1., 2.]],
 
          [[1., 2.],
           [1., 2.],
           [1., 2.],
           [1., 2.]]]]),
 torch.Size([1, 3, 4, 2]))

### `torch.flatten` 展平

In [3]:
a = torch.randn(2, 3, 4, 5)
a.shape

torch.Size([2, 3, 4, 5])

In [4]:
x = a.flatten(1, 2)
x.shape

torch.Size([2, 12, 5])

In [5]:
# pytorch 中 - 表示从后向前数 
x = a.flatten(-2) # 合并后两维
x.shape

torch.Size([2, 3, 20])